# Generated by Django 4.2.1 on 2023-07-09 19:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tg_bot.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sketches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='sketches', verbose_name='Фотография')),
                ('complexity', models.IntegerField(default=0, verbose_name='Сложность эскиза')),
                ('famous', models.IntegerField(default=0, verbose_name='Популярность эскиза')),
            ],
            options={
                'verbose_name': 'Эскиз',
                'verbose_name_plural': 'Эскизы',
            },
        ),
        migrations.CreateModel(
            name='TattooPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название места татуировки')),
                ('pain_level', models.IntegerField(verbose_name='Уровень боли')),
            ],
            options={
                'verbose_name': 'Место для татуировки',
                'verbose_name_plural': 'Места для татуировок',
            },
        ),
        migrations.AlterModelOptions(
            name='bookingtime',
            options={'verbose_name': 'Время консультаций', 'verbose_name_plural': 'Время консультаций'},
        ),
        migrations.AlterModelOptions(
            name='dates',
            options={'verbose_name': 'Дата бесплатной консультации',
                     'verbose_name_plural': 'Даты бесплатных консультаций'},
        ),
        migrations.AlterModelOptions(
            name='tgusers',
            options={'verbose_name': 'Пользователь ТГ', 'verbose_name_plural': 'Пользователи ТГ'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'Моя работа', 'verbose_name_plural': 'Мои работы'},
        ),
        migrations.RemoveField(
            model_name='works',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='works',
            name='photo_pass',
        ),
        migrations.AddField(
            model_name='works',
            name='date',
            field=models.DateField(
                default=datetime.datetime(2023, 7, 9, 19, 43, 11, 760073, tzinfo=datetime.timezone.utc),
                verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='works',
            name='name',
            field=models.CharField(
                default=datetime.datetime(2023, 7, 9, 19, 43, 21, 911474, tzinfo=datetime.timezone.utc), max_length=255,
                verbose_name='Название татуировки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='works',
            name='pain_level',
            field=models.IntegerField(
                choices=[('1', 'Низкий уровень боли'), ('2', 'Средний уровень боли'), ('3', 'Высокий уровень боли')],
                default=1, verbose_name='Уровень боли'),
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='expert',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='booking_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='time',
            field=tg_bot.models.CustomTimeField(
                choices=[('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'),
                         ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'),
                         ('19:00', '19:00')], default='free'),
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='booking_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='status',
            field=models.CharField(choices=[('free', 'Свободный день'), ('partially_booked', 'Частично занят'),
                                            ('fully_booked', 'Полностью занят'), ('day_off', 'Выходной')],
                                   default='free', max_length=40, verbose_name='Статус дня'),
        ),
        migrations.AlterField(
            model_name='tgusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tgusers',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='tgusers',
            name='tg_id',
            field=models.IntegerField(verbose_name='tg_id'),
        ),
        migrations.AlterField(
            model_name='works',
            name='photo',
            field=models.ImageField(upload_to='works', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='works',
            name='place',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='tg_bot.tattooplace',
                                       verbose_name='Место татуировки'),
        ),
    ]
