# Generated by Django 4.2.1 on 2023-07-09 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tg_bot', '0002_sketches_tattooplace_delete_newtattoo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(
                default=datetime.datetime(2023, 7, 9, 19, 50, 49, 291554, tzinfo=datetime.timezone.utc),
                verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='works',
            name='pain_level',
            field=models.CharField(
                choices=[('1', 'Низкий уровень боли'), ('2', 'Средний уровень боли'), ('3', 'Высокий уровень боли')],
                default=1, max_length=40, verbose_name='Уровень боли'),
        ),
    ]
