# Generated by Django 4.2.1 on 2023-07-09 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_delete_newtattoo_alter_works_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сообщения')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Текстовые сообщения в бота',
                'verbose_name_plural': 'Текстовые сообщения в бота',
            },
        ),
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 21, 44, 15, 998488, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 21, 44, 15, 996719, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
