# Generated by Django 4.2.1 on 2023-07-10 01:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_favouritestickers_feedback_messages_sticker_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='TechnicalMessages',
        ),
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 1, 14, 28, 713601, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 1, 14, 28, 713098, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='AllMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текс сообщения')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время сообщения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.tgusers')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Все сообщения',
            },
        ),
    ]
