# Generated by Django 4.2.1 on 2023-07-11 06:00

import datetime
from django.db import migrations, models
import tg_bot.models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0007_alter_dates_date_alter_works_date_bannedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='time',
            field=tg_bot.models.CustomTimeField(choices=[('11', '11:00'), ('12', '12:00'), ('13', '13:00'), ('14', '14:00'), ('15', '15:00'), ('16', '16:00'), ('17', '17:00'), ('18', '18:00'), ('19', '19:00'), ('20', '20:00')]),
        ),
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 6, 0, 36, 606353, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 6, 0, 36, 605633, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
